site_name: Geonovum tooling
theme:
    name: readthedocs
repo_url: https://github.com/Geonovum/handleiding-tooling
edit_uri: blob/main/docs/

nav:
    - Home:
        - 'Welkom': index.md
        - 'Werkwijze Modelleren': werkwijzemodelleren.md
        - 'Tooling' : tooling.md
        - 'Verdere documentatie': werkwijze-todo.md
    - GitHub:
        - 'Manual': GitHub/index.md
        - 'GitHub intro': GitHub/GitHub-Inleiding.md
        - 'GitHub beheer' : Github/GitHub-beheer.md
    - Imvertor:
        - Imvertor/index.md
    - Markdown:
        - Markdown/index.md
    - ReSpec:
        - Manual: ReSpec/index.md
        - Publiceren: ReSpec/ReSpec-publiceren.md
        - Onderdelen van ReSpec: ReSpec/ReSpec-onderdelen.md
    - Enterprise Architect:
        - Overzicht: EA/index.md
        - Toolbox importeren: EA/MIM-toolbox-importeren.md
        - standaarddatatypen: EA/EA-toepassing-standaarddatatypen.md
        - Toolbox genereren: EA/MIM-toolbox-genereren.md
        - Toolbox genereren extensie: EA/MIM-toolbox-genereren-extensie.md
        - XMI exporteren: EA/xmi-exporteren.md
    - UML:
        - UML: UML/index.md
        - Leeswijzer UML: UML/UML-leeswijzer.md
    - Subversion:
        - SVN: svn/index.md
        - SVN installeren voor EAP: svn/SVN-installeren-voor-EAP.md
        - 'SVN importeren bestaand project': svn/SVN-importeren-bestaand-project.md
    - GML:
        - GML/index.md
    - MIM:
        - MIM/index.md
    - Conceptenbibliotheek:
        - Begrippen/index.md
        - Begrippen/BegrippenXL.md
    - RDF:
        - RDF/index.md
    - Ontologie:
        - Ontologie/index.md
    - Word2xxx:
        - Word2xxx/index.md
    - Schemas maken:
        - schemas/JSON.md
